/**
 * Apply structured "actions" returned by the AI assistant against MongoDB.
 *
 * The AI service `/chat` endpoint may include an `actions` array describing
 * side-effects the assistant wants to perform (e.g. add a recipe to the
 * weekly plan). This module:
 *   1. Validates each action's shape.
 *   2. Resolves recipe references (slug / title fuzzy match).
 *   3. Mutates the appropriate MealPlan document (find-or-create).
 *   4. Broadcasts the realtime event so other tabs / devices refresh.
 *   5. Returns `appliedActions` enriched with the resolved recipe, calories,
 *      and ingredient list — the client renders these as confirmation cards.
 *
 * Failures (recipe not found, validation errors, db errors) are reported as
 * non-throwing entries in `appliedActions` so the chat reply itself never
 * fails just because the assistant asked for something impossible.
 */
import { Types } from 'mongoose';
import { MealPlan, DAYS_OF_WEEK, type DayOfWeek, type IDayPlan } from '../models/MealPlan';
import { Recipe, type IRecipe, type IRecipeIngredient } from '../models/Recipe';
import { GroceryList } from '../models/GroceryList';
import { aggregateGroceryItems, collectRecipesFromPlan } from '../utils/groceryAggregator';
import { broadcastMealPlan } from './realtime';
import { generateRecipe, type GeneratedRecipe } from './aiClient';
import { logger } from '../config/logger';

const DAY_SET = new Set<DayOfWeek>(DAYS_OF_WEEK);
const SLOTS = ['breakfast', 'lunch', 'dinner'] as const;
type Slot = (typeof SLOTS)[number];

export interface RawAction {
  type?: string;
  recipe_query?: string;
  day?: string;
  slot?: string;
  week_offset?: number;
}

export interface AppliedAction {
  type: 'add_to_plan';
  status: 'applied' | 'recipe_not_found' | 'invalid' | 'error';
  requested: {
    recipe_query: string;
    day: DayOfWeek | string;
    slot: Slot | string;
    week_offset: number;
  };
  recipe?: {
    id: string;
    slug: string;
    title: string;
    calories: number | null;
    ingredients: Array<{ name: string; quantity?: number; unit?: string }>;
    imageUrl?: string;
    /** True when this recipe was newly generated by the LLM for this request. */
    generated?: boolean;
  };
  mealPlanId?: string;
  weekStartDate?: string;
  message?: string;
}

/** Per-user context forwarded from the chat route. */
export interface ChatActionContext {
  dietaryPreferences: string[];
  allergies: string[];
}

/** Monday-aligned start of the week (UTC) for the given date. */
function mondayOfWeek(d: Date): Date {
  const day = d.getUTCDay(); // 0 = Sunday … 6 = Saturday
  const offsetToMonday = day === 0 ? -6 : 1 - day;
  const monday = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
  monday.setUTCDate(monday.getUTCDate() + offsetToMonday);
  return monday;
}

function targetWeekStart(weekOffset: number): Date {
  const monday = mondayOfWeek(new Date());
  monday.setUTCDate(monday.getUTCDate() + weekOffset * 7);
  return monday;
}

function slugifyQuery(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function escapeRegex(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Generic culinary adjectives, cuisine names, meal-time labels and other
 * filler words. When the user says "spicy indian lobster masala", these
 * tokens are NOT useful for fuzzy-matching against the recipe library
 * because they'd match dozens of unrelated dishes (e.g. "spicy" would
 * collide with "Spicy Tuna Sushi Bowl"). We strip them before scoring.
 */
const MATCH_STOPWORDS = new Set<string>([
  // Quality / heat / texture adjectives
  'spicy', 'mild', 'medium', 'hot', 'sweet', 'savory', 'savoury', 'salty',
  'sour', 'bitter', 'tangy', 'creamy', 'crispy', 'crunchy', 'tender', 'juicy',
  // Difficulty / time / health adjectives
  'easy', 'quick', 'simple', 'fast', 'classic', 'traditional', 'authentic',
  'healthy', 'hearty', 'light', 'fresh', 'homemade', 'gourmet', 'fancy',
  'best', 'perfect', 'ultimate', 'amazing', 'delicious', 'tasty',
  // Cuisine / region words
  'indian', 'italian', 'asian', 'chinese', 'japanese', 'mexican', 'french',
  'american', 'korean', 'vietnamese', 'thai', 'mediterranean', 'european',
  'southern', 'northern', 'eastern', 'western', 'greek', 'turkish', 'spanish',
  'moroccan', 'lebanese', 'persian',
  // Meal slots / serving style
  'breakfast', 'brunch', 'lunch', 'dinner', 'supper', 'snack', 'dessert',
  'appetizer', 'starter', 'side', 'main', 'course',
  // Filler
  'style', 'recipe', 'dish', 'meal', 'food', 'with', 'and', 'the', 'for',
  'new', 'old', 'real',
]);

function significantTokens(query: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of query.toLowerCase().split(/\s+/)) {
    const t = raw.replace(/[^a-z0-9]/g, '');
    if (t.length < 4) continue;
    if (MATCH_STOPWORDS.has(t)) continue;
    if (seen.has(t)) continue;
    seen.add(t);
    out.push(t);
  }
  return out;
}

/** Find a recipe matching the LLM-provided query, with several fallbacks. */
async function resolveRecipe(query: string): Promise<IRecipe & { _id: Types.ObjectId } | null> {
  const trimmed = query.trim();
  if (!trimmed) return null;
  const slug = slugifyQuery(trimmed);

  // 1. Exact slug match (fastest, indexed).
  if (slug) {
    const bySlug = await Recipe.findOne({ slug });
    if (bySlug) return bySlug as IRecipe & { _id: Types.ObjectId };
  }

  // 2. Exact title (case-insensitive).
  const exactTitle = await Recipe.findOne({
    title: new RegExp(`^${escapeRegex(trimmed)}$`, 'i'),
  });
  if (exactTitle) return exactTitle as IRecipe & { _id: Types.ObjectId };

  // 3. Whole-query substring on title (e.g. "chicken biryani" -> "Chicken Biryani Bowl").
  const substring = await Recipe.find({
    title: new RegExp(escapeRegex(trimmed), 'i'),
  })
    .sort({ title: 1 })
    .limit(5);
  if (substring.length > 0) {
    substring.sort((a, b) => a.title.length - b.title.length);
    return substring[0] as IRecipe & { _id: Types.ObjectId };
  }

  // 4. Token-overlap fallback with stopword filtering and multi-token scoring.
  //    Previously this returned the first hit on the LONGEST single token,
  //    which caused generic adjectives ("spicy", "indian") to match unrelated
  //    recipes. We now require either:
  //      (a) the candidate title to contain >= 2 distinct significant tokens, OR
  //      (b) the query has a single significant token and that token is
  //          specific enough (>= 6 chars, e.g. "biryani", "carbonara").
  //    Otherwise we return null and let the caller fall through to AI
  //    generation, which produces a real recipe for the requested dish.
  const tokens = significantTokens(trimmed);
  if (tokens.length === 0) return null;

  const orPattern = tokens.map(escapeRegex).join('|');
  const candidates = await Recipe.find({ title: new RegExp(orPattern, 'i') }).limit(50);

  let best: (IRecipe & { _id: Types.ObjectId }) | null = null;
  let bestScore = 0;
  let bestTitleLen = Number.POSITIVE_INFINITY;
  for (const c of candidates) {
    const title = c.title.toLowerCase();
    const score = tokens.reduce((acc, t) => (title.includes(t) ? acc + 1 : acc), 0);
    if (score > bestScore || (score === bestScore && title.length < bestTitleLen)) {
      best = c as IRecipe & { _id: Types.ObjectId };
      bestScore = score;
      bestTitleLen = title.length;
    }
  }

  if (!best) return null;
  if (bestScore >= 2) return best;
  if (bestScore === 1 && tokens.length === 1 && (tokens[0]?.length ?? 0) >= 6) return best;
  return null;
}

function isDay(value: unknown): value is DayOfWeek {
  return typeof value === 'string' && DAY_SET.has(value as DayOfWeek);
}

function isSlot(value: unknown): value is Slot {
  return typeof value === 'string' && (SLOTS as readonly string[]).includes(value);
}

/**
 * Persist an LLM-generated recipe into the Recipe collection. Uses upsert on
 * the slug so two requests for the same dish reuse the existing document
 * instead of failing on the unique index. Returns the saved doc, or `null`
 * if the LLM produced an unusable payload.
 */
export async function saveGeneratedRecipe(
  userId: string,
  gen: GeneratedRecipe
): Promise<(IRecipe & { _id: Types.ObjectId }) | null> {
  if (!gen.title?.trim() || !gen.ingredients?.length || !gen.instructions?.length) {
    return null;
  }
  const slug = slugifyQuery(gen.title);
  if (!slug) return null;

  try {
    // If a recipe with this slug already exists, prefer it (avoid duplicates).
    const existing = await Recipe.findOne({ slug });
    if (existing) return existing as IRecipe & { _id: Types.ObjectId };

    const doc = await Recipe.create({
      title: gen.title.trim().slice(0, 200),
      slug,
      description: (gen.description ?? '').slice(0, 2000),
      ingredients: (gen.ingredients ?? []).map((i) => ({
        name: String(i.name ?? '').toLowerCase().trim().slice(0, 100),
        quantity: typeof i.quantity === 'number' && i.quantity >= 0 ? i.quantity : undefined,
        unit: i.unit ? String(i.unit).toLowerCase().trim().slice(0, 20) : undefined,
      })),
      instructions: (gen.instructions ?? []).map((s) => String(s)).filter(Boolean),
      cuisine: gen.cuisine ? String(gen.cuisine).toLowerCase().trim().slice(0, 50) : undefined,
      tags: (gen.tags ?? []).map((t) => String(t).toLowerCase()).slice(0, 20),
      prepTime: Math.max(0, Math.min(1440, Math.trunc(gen.prep_time ?? 0))),
      cookTime: Math.max(0, Math.min(1440, Math.trunc(gen.cook_time ?? 0))),
      servings: Math.max(1, Math.min(100, Math.trunc(gen.servings ?? 2))),
      nutrition: {
        calories: gen.nutrition?.calories ?? undefined,
        protein: gen.nutrition?.protein ?? undefined,
        carbs: gen.nutrition?.carbs ?? undefined,
        fat: gen.nutrition?.fat ?? undefined,
        fiber: gen.nutrition?.fiber ?? undefined,
        sugar: gen.nutrition?.sugar ?? undefined,
        sodium: gen.nutrition?.sodium ?? undefined,
      },
      imageUrl: gen.image_url ?? undefined,
      source: gen.source ?? 'ai-generated',
      difficulty: gen.difficulty ?? 'medium',
      createdBy: new Types.ObjectId(userId),
    });
    return doc as IRecipe & { _id: Types.ObjectId };
  } catch (err) {
    logger.error({ err, title: gen.title }, 'chatActions: failed to persist generated recipe');
    return null;
  }
}

/**
 * Re-aggregate the meal plan's recipes into a grocery list and upsert it.
 *
 * Called after the assistant adds a recipe to a plan so the user's shopping
 * list stays in sync without a manual "Generate" click. If a list already
 * exists for this (user, plan), we update its items in place and preserve
 * the `checked` flag for any ingredient that's still present after the
 * re-aggregation.
 */
async function upsertGroceryListForPlan(
  userId: string,
  mealPlanId: Types.ObjectId,
  weekStartDate: Date
): Promise<void> {
  const populated = await MealPlan.findById(mealPlanId).populate(
    'days.breakfast days.lunch days.dinner days.snacks',
    'ingredients servings title'
  );
  if (!populated) return;

  const recipes = collectRecipesFromPlan(
    populated.days as unknown as Parameters<typeof collectRecipesFromPlan>[0]
  );
  if (recipes.length === 0) return;

  const newItems = aggregateGroceryItems(recipes);
  const existing = await GroceryList.findOne({
    user: new Types.ObjectId(userId),
    mealPlan: mealPlanId,
  });

  if (existing) {
    const checkedMap = new Map<string, boolean>();
    for (const item of existing.items) {
      checkedMap.set(`${item.ingredient}::${item.unit ?? ''}`, item.checked);
    }
    for (const item of newItems) {
      const key = `${item.ingredient}::${item.unit ?? ''}`;
      if (checkedMap.has(key)) item.checked = checkedMap.get(key) ?? false;
    }
    existing.set('items', newItems);
    existing.generatedAt = new Date();
    await existing.save();
    return;
  }

  await GroceryList.create({
    user: new Types.ObjectId(userId),
    mealPlan: mealPlanId,
    name: `Groceries for week of ${weekStartDate.toISOString().slice(0, 10)}`,
    items: newItems,
  });
}

/**
 * If the LLM emits a compound query like "fresh fruit salad and nutella
 * bread", Gemini may refuse / return empty because it can't produce one
 * coherent recipe for two unrelated dishes. We make one retry with a
 * simplified query (the first half before " and / with / plus ").
 *
 * Returns the simplified query (different from the original) or null if no
 * useful simplification could be derived.
 */
function simplifyCompoundQuery(query: string): string | null {
  const trimmed = query.trim();
  if (!trimmed) return null;
  // Split on " and " / " with " / " plus " / " & " (whole words, case-insensitive).
  const m = trimmed.split(/\s+(?:and|with|plus|&)\s+/i);
  if (m.length >= 2) {
    const head = m[0]?.trim();
    if (head && head.length >= 3 && head.toLowerCase() !== trimmed.toLowerCase()) {
      return head;
    }
  }
  // Otherwise, if the query is unusually long (>= 7 words), take the last 4.
  const words = trimmed.split(/\s+/).filter(Boolean);
  if (words.length >= 7) {
    const tail = words.slice(-4).join(' ');
    if (tail.toLowerCase() !== trimmed.toLowerCase()) return tail;
  }
  return null;
}

/**
 * Wrap `generateRecipe` with a single retry on simplified-query failure.
 * Returns the GenerateRecipeResponse from the FIRST attempt that yielded a
 * usable recipe, or the last (failed) response otherwise.
 */
export async function generateRecipeWithRetry(
  query: string,
  options: { dietary_preferences?: string[]; allergies?: string[] } = {}
): Promise<{ result: Awaited<ReturnType<typeof generateRecipe>>; usedQuery: string }>
{
  const first = await generateRecipe({ query, ...options });
  if (first.success && first.recipe) {
    return { result: first, usedQuery: query };
  }
  const fallbackQuery = simplifyCompoundQuery(query);
  if (!fallbackQuery) return { result: first, usedQuery: query };
  logger.info(
    { originalQuery: query, fallbackQuery, message: first.message },
    'chatActions: retrying recipe generation with simplified query'
  );
  const second = await generateRecipe({ query: fallbackQuery, ...options });
  if (second.success && second.recipe) {
    return { result: second, usedQuery: fallbackQuery };
  }
  // Both attempts failed — surface the first failure (better signal).
  return { result: first, usedQuery: query };
}

async function applyAddToPlan(
  userId: string,
  ctx: ChatActionContext,
  raw: RawAction
): Promise<AppliedAction> {
  const recipeQuery = String(raw.recipe_query ?? '').trim();
  const dayRaw = String(raw.day ?? '');
  const slotRaw = String(raw.slot ?? '').toLowerCase();
  const weekOffset = Number.isFinite(raw.week_offset)
    ? Math.max(0, Math.min(8, Math.trunc(raw.week_offset as number)))
    : 0;

  const requested = {
    recipe_query: recipeQuery,
    day: dayRaw,
    slot: slotRaw,
    week_offset: weekOffset,
  };

  if (!recipeQuery || !isDay(dayRaw) || !isSlot(slotRaw)) {
    return {
      type: 'add_to_plan',
      status: 'invalid',
      requested,
      message: 'Action was missing a valid recipe, day, or meal slot.',
    };
  }

  let recipe = await resolveRecipe(recipeQuery);
  let wasGenerated = false;

  // No library match → ask the AI service to draft a full recipe and persist
  // it before assigning. Honours the user's dietary preferences + allergies.
  // We retry once with a simplified query if the model rejects a compound
  // request like "fresh fruit salad and nutella bread".
  if (!recipe) {
    try {
      const { result: gen, usedQuery } = await generateRecipeWithRetry(recipeQuery, {
        dietary_preferences: ctx.dietaryPreferences,
        allergies: ctx.allergies,
      });
      if (gen.success && gen.recipe) {
        const saved = await saveGeneratedRecipe(userId, gen.recipe);
        if (saved) {
          recipe = saved;
          wasGenerated = true;
        }
      } else if (gen.message) {
        logger.info(
          { query: recipeQuery, usedQuery, message: gen.message },
          'chatActions: generator declined to produce a recipe'
        );
      }
    } catch (err) {
      logger.error({ err, query: recipeQuery }, 'chatActions: generator call failed');
    }
  }

  if (!recipe) {
    return {
      type: 'add_to_plan',
      status: 'recipe_not_found',
      requested,
      message: `Couldn't find or generate a recipe for "${recipeQuery}". Try a more specific name or add it on the Recipes page.`,
    };
  }

  try {
    const weekStartDate = targetWeekStart(weekOffset);
    const defaultDays: IDayPlan[] = DAYS_OF_WEEK.map((d) => ({
      day: d,
      snacks: [] as Types.ObjectId[],
    }));

    const plan = await MealPlan.findOneAndUpdate(
      { user: new Types.ObjectId(userId), weekStartDate },
      { $setOnInsert: { days: defaultDays, user: new Types.ObjectId(userId), weekStartDate } },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );

    let dayDoc = plan.days.find((d) => d.day === dayRaw);
    if (!dayDoc) {
      dayDoc = { day: dayRaw, snacks: [] } as IDayPlan;
      plan.days.push(dayDoc);
    }
    if (slotRaw === 'breakfast') dayDoc.breakfast = recipe._id;
    else if (slotRaw === 'lunch') dayDoc.lunch = recipe._id;
    else dayDoc.dinner = recipe._id;

    await plan.save();
    broadcastMealPlan({
      type: 'mealplan:updated',
      mealPlanId: String(plan._id),
      payload: plan,
      actorId: userId,
    });

    // Best-effort: keep the grocery list for this plan in sync so the user
    // doesn't have to click "Generate grocery list" again every time the
    // assistant adds a recipe. Failures are swallowed — the meal-plan
    // update itself must always succeed.
    try {
      await upsertGroceryListForPlan(userId, plan._id, weekStartDate);
    } catch (err) {
      logger.warn({ err, mealPlanId: String(plan._id) }, 'chatActions: grocery sync failed');
    }

    return {
      type: 'add_to_plan',
      status: 'applied',
      requested,
      recipe: {
        id: String(recipe._id),
        slug: recipe.slug,
        title: recipe.title,
        calories: recipe.nutrition?.calories ?? null,
        ingredients: (recipe.ingredients ?? []).map((i: IRecipeIngredient) => ({
          name: i.name,
          quantity: i.quantity,
          unit: i.unit,
        })),
        imageUrl: recipe.imageUrl,
        generated: wasGenerated,
      },
      mealPlanId: String(plan._id),
      weekStartDate: weekStartDate.toISOString(),
      message: wasGenerated
        ? `Generated "${recipe.title}" and added it to ${dayRaw} ${slotRaw}.`
        : `Added "${recipe.title}" to ${dayRaw} ${slotRaw}.`,
    };
  } catch (err) {
    logger.error({ err }, 'chatActions: failed to apply add_to_plan');
    return {
      type: 'add_to_plan',
      status: 'error',
      requested,
      message: 'Could not update the meal plan — please try again.',
    };
  }
}

/**
 * Apply each action from the AI service. Unknown action types are silently
 * skipped (forward-compatible). Failures are reported per-action rather than
 * thrown so the chat reply itself always succeeds.
 */
export async function applyChatActions(
  userId: string,
  ctx: ChatActionContext,
  actions: RawAction[] | undefined
): Promise<AppliedAction[]> {
  if (!Array.isArray(actions) || actions.length === 0) return [];
  const out: AppliedAction[] = [];
  // Cap so a misbehaving model can't queue up dozens of writes.
  for (const raw of actions.slice(0, 4)) {
    if (raw && raw.type === 'add_to_plan') {
      out.push(await applyAddToPlan(userId, ctx, raw));
    }
  }
  return out;
}
