/**
 * Apply structured "actions" returned by the AI assistant against MongoDB.
 *
 * The AI service `/chat` endpoint may include an `actions` array describing
 * side-effects the assistant wants to perform (e.g. add a recipe to the
 * weekly plan). This module:
 *   1. Validates each action's shape.
 *   2. Resolves recipe references (slug / title fuzzy match).
 *   3. Mutates the appropriate MealPlan document (find-or-create).
 *   4. Broadcasts the realtime event so other tabs / devices refresh.
 *   5. Returns `appliedActions` enriched with the resolved recipe, calories,
 *      and ingredient list — the client renders these as confirmation cards.
 *
 * Failures (recipe not found, validation errors, db errors) are reported as
 * non-throwing entries in `appliedActions` so the chat reply itself never
 * fails just because the assistant asked for something impossible.
 */
import { Types } from 'mongoose';
import { MealPlan, DAYS_OF_WEEK, type DayOfWeek, type IDayPlan } from '../models/MealPlan';
import { Recipe, type IRecipe, type IRecipeIngredient } from '../models/Recipe';
import { broadcastMealPlan } from './realtime';
import { generateRecipe, type GeneratedRecipe } from './aiClient';
import { logger } from '../config/logger';

const DAY_SET = new Set<DayOfWeek>(DAYS_OF_WEEK);
const SLOTS = ['breakfast', 'lunch', 'dinner'] as const;
type Slot = (typeof SLOTS)[number];

export interface RawAction {
  type?: string;
  recipe_query?: string;
  day?: string;
  slot?: string;
  week_offset?: number;
}

export interface AppliedAction {
  type: 'add_to_plan';
  status: 'applied' | 'recipe_not_found' | 'invalid' | 'error';
  requested: {
    recipe_query: string;
    day: DayOfWeek | string;
    slot: Slot | string;
    week_offset: number;
  };
  recipe?: {
    id: string;
    slug: string;
    title: string;
    calories: number | null;
    ingredients: Array<{ name: string; quantity?: number; unit?: string }>;
    imageUrl?: string;
    /** True when this recipe was newly generated by the LLM for this request. */
    generated?: boolean;
  };
  mealPlanId?: string;
  weekStartDate?: string;
  message?: string;
}

/** Per-user context forwarded from the chat route. */
export interface ChatActionContext {
  dietaryPreferences: string[];
  allergies: string[];
}

/** Monday-aligned start of the week (UTC) for the given date. */
function mondayOfWeek(d: Date): Date {
  const day = d.getUTCDay(); // 0 = Sunday … 6 = Saturday
  const offsetToMonday = day === 0 ? -6 : 1 - day;
  const monday = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
  monday.setUTCDate(monday.getUTCDate() + offsetToMonday);
  return monday;
}

function targetWeekStart(weekOffset: number): Date {
  const monday = mondayOfWeek(new Date());
  monday.setUTCDate(monday.getUTCDate() + weekOffset * 7);
  return monday;
}

function slugifyQuery(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function escapeRegex(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Find a recipe matching the LLM-provided query, with several fallbacks. */
async function resolveRecipe(query: string): Promise<IRecipe & { _id: Types.ObjectId } | null> {
  const trimmed = query.trim();
  if (!trimmed) return null;
  const slug = slugifyQuery(trimmed);

  // 1. Exact slug match (fastest, indexed).
  if (slug) {
    const bySlug = await Recipe.findOne({ slug });
    if (bySlug) return bySlug as IRecipe & { _id: Types.ObjectId };
  }

  // 2. Exact title (case-insensitive).
  const exactTitle = await Recipe.findOne({
    title: new RegExp(`^${escapeRegex(trimmed)}$`, 'i'),
  });
  if (exactTitle) return exactTitle as IRecipe & { _id: Types.ObjectId };

  // 3. Substring on title — pick the shortest match (closest to the query).
  const substring = await Recipe.find({
    title: new RegExp(escapeRegex(trimmed), 'i'),
  })
    .sort({ title: 1 })
    .limit(5);
  if (substring.length > 0) {
    substring.sort((a, b) => a.title.length - b.title.length);
    return substring[0] as IRecipe & { _id: Types.ObjectId };
  }

  // 4. Token-overlap fallback — split the query into significant words and
  //    look for recipes whose title contains the longest one. Helps when the
  //    user names a regional dish but the DB has a different exact name
  //    (e.g. "biryani" -> "Chicken Biryani Bowl").
  const tokens = trimmed
    .split(/\s+/)
    .map((t) => t.replace(/[^a-z0-9]/gi, ''))
    .filter((t) => t.length >= 4)
    .sort((a, b) => b.length - a.length);
  for (const token of tokens) {
    const hit = await Recipe.findOne({
      title: new RegExp(escapeRegex(token), 'i'),
    });
    if (hit) return hit as IRecipe & { _id: Types.ObjectId };
  }
  return null;
}

function isDay(value: unknown): value is DayOfWeek {
  return typeof value === 'string' && DAY_SET.has(value as DayOfWeek);
}

function isSlot(value: unknown): value is Slot {
  return typeof value === 'string' && (SLOTS as readonly string[]).includes(value);
}

/**
 * Persist an LLM-generated recipe into the Recipe collection. Uses upsert on
 * the slug so two requests for the same dish reuse the existing document
 * instead of failing on the unique index. Returns the saved doc, or `null`
 * if the LLM produced an unusable payload.
 */
async function saveGeneratedRecipe(
  userId: string,
  gen: GeneratedRecipe
): Promise<(IRecipe & { _id: Types.ObjectId }) | null> {
  if (!gen.title?.trim() || !gen.ingredients?.length || !gen.instructions?.length) {
    return null;
  }
  const slug = slugifyQuery(gen.title);
  if (!slug) return null;

  try {
    // If a recipe with this slug already exists, prefer it (avoid duplicates).
    const existing = await Recipe.findOne({ slug });
    if (existing) return existing as IRecipe & { _id: Types.ObjectId };

    const doc = await Recipe.create({
      title: gen.title.trim().slice(0, 200),
      slug,
      description: (gen.description ?? '').slice(0, 2000),
      ingredients: (gen.ingredients ?? []).map((i) => ({
        name: String(i.name ?? '').toLowerCase().trim().slice(0, 100),
        quantity: typeof i.quantity === 'number' && i.quantity >= 0 ? i.quantity : undefined,
        unit: i.unit ? String(i.unit).toLowerCase().trim().slice(0, 20) : undefined,
      })),
      instructions: (gen.instructions ?? []).map((s) => String(s)).filter(Boolean),
      cuisine: gen.cuisine ? String(gen.cuisine).toLowerCase().trim().slice(0, 50) : undefined,
      tags: (gen.tags ?? []).map((t) => String(t).toLowerCase()).slice(0, 20),
      prepTime: Math.max(0, Math.min(1440, Math.trunc(gen.prep_time ?? 0))),
      cookTime: Math.max(0, Math.min(1440, Math.trunc(gen.cook_time ?? 0))),
      servings: Math.max(1, Math.min(100, Math.trunc(gen.servings ?? 2))),
      nutrition: {
        calories: gen.nutrition?.calories ?? undefined,
        protein: gen.nutrition?.protein ?? undefined,
        carbs: gen.nutrition?.carbs ?? undefined,
        fat: gen.nutrition?.fat ?? undefined,
        fiber: gen.nutrition?.fiber ?? undefined,
        sugar: gen.nutrition?.sugar ?? undefined,
        sodium: gen.nutrition?.sodium ?? undefined,
      },
      imageUrl: gen.image_url ?? undefined,
      source: gen.source ?? 'ai-generated',
      difficulty: gen.difficulty ?? 'medium',
      createdBy: new Types.ObjectId(userId),
    });
    return doc as IRecipe & { _id: Types.ObjectId };
  } catch (err) {
    logger.error({ err, title: gen.title }, 'chatActions: failed to persist generated recipe');
    return null;
  }
}

async function applyAddToPlan(
  userId: string,
  ctx: ChatActionContext,
  raw: RawAction
): Promise<AppliedAction> {
  const recipeQuery = String(raw.recipe_query ?? '').trim();
  const dayRaw = String(raw.day ?? '');
  const slotRaw = String(raw.slot ?? '').toLowerCase();
  const weekOffset = Number.isFinite(raw.week_offset)
    ? Math.max(0, Math.min(8, Math.trunc(raw.week_offset as number)))
    : 0;

  const requested = {
    recipe_query: recipeQuery,
    day: dayRaw,
    slot: slotRaw,
    week_offset: weekOffset,
  };

  if (!recipeQuery || !isDay(dayRaw) || !isSlot(slotRaw)) {
    return {
      type: 'add_to_plan',
      status: 'invalid',
      requested,
      message: 'Action was missing a valid recipe, day, or meal slot.',
    };
  }

  let recipe = await resolveRecipe(recipeQuery);
  let wasGenerated = false;

  // No library match → ask the AI service to draft a full recipe and persist
  // it before assigning. Honours the user's dietary preferences + allergies.
  if (!recipe) {
    try {
      const gen = await generateRecipe({
        query: recipeQuery,
        dietary_preferences: ctx.dietaryPreferences,
        allergies: ctx.allergies,
      });
      if (gen.success && gen.recipe) {
        const saved = await saveGeneratedRecipe(userId, gen.recipe);
        if (saved) {
          recipe = saved;
          wasGenerated = true;
        }
      } else if (gen.message) {
        logger.info(
          { query: recipeQuery, message: gen.message },
          'chatActions: generator declined to produce a recipe'
        );
      }
    } catch (err) {
      logger.error({ err, query: recipeQuery }, 'chatActions: generator call failed');
    }
  }

  if (!recipe) {
    return {
      type: 'add_to_plan',
      status: 'recipe_not_found',
      requested,
      message: `Couldn't find or generate a recipe for "${recipeQuery}". Try a more specific name or add it on the Recipes page.`,
    };
  }

  try {
    const weekStartDate = targetWeekStart(weekOffset);
    const defaultDays: IDayPlan[] = DAYS_OF_WEEK.map((d) => ({
      day: d,
      snacks: [] as Types.ObjectId[],
    }));

    const plan = await MealPlan.findOneAndUpdate(
      { user: new Types.ObjectId(userId), weekStartDate },
      { $setOnInsert: { days: defaultDays, user: new Types.ObjectId(userId), weekStartDate } },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );

    let dayDoc = plan.days.find((d) => d.day === dayRaw);
    if (!dayDoc) {
      dayDoc = { day: dayRaw, snacks: [] } as IDayPlan;
      plan.days.push(dayDoc);
    }
    if (slotRaw === 'breakfast') dayDoc.breakfast = recipe._id;
    else if (slotRaw === 'lunch') dayDoc.lunch = recipe._id;
    else dayDoc.dinner = recipe._id;

    await plan.save();
    broadcastMealPlan({
      type: 'mealplan:updated',
      mealPlanId: String(plan._id),
      payload: plan,
      actorId: userId,
    });

    return {
      type: 'add_to_plan',
      status: 'applied',
      requested,
      recipe: {
        id: String(recipe._id),
        slug: recipe.slug,
        title: recipe.title,
        calories: recipe.nutrition?.calories ?? null,
        ingredients: (recipe.ingredients ?? []).map((i: IRecipeIngredient) => ({
          name: i.name,
          quantity: i.quantity,
          unit: i.unit,
        })),
        imageUrl: recipe.imageUrl,
        generated: wasGenerated,
      },
      mealPlanId: String(plan._id),
      weekStartDate: weekStartDate.toISOString(),
      message: wasGenerated
        ? `Generated "${recipe.title}" and added it to ${dayRaw} ${slotRaw}.`
        : `Added "${recipe.title}" to ${dayRaw} ${slotRaw}.`,
    };
  } catch (err) {
    logger.error({ err }, 'chatActions: failed to apply add_to_plan');
    return {
      type: 'add_to_plan',
      status: 'error',
      requested,
      message: 'Could not update the meal plan — please try again.',
    };
  }
}

/**
 * Apply each action from the AI service. Unknown action types are silently
 * skipped (forward-compatible). Failures are reported per-action rather than
 * thrown so the chat reply itself always succeeds.
 */
export async function applyChatActions(
  userId: string,
  ctx: ChatActionContext,
  actions: RawAction[] | undefined
): Promise<AppliedAction[]> {
  if (!Array.isArray(actions) || actions.length === 0) return [];
  const out: AppliedAction[] = [];
  // Cap so a misbehaving model can't queue up dozens of writes.
  for (const raw of actions.slice(0, 4)) {
    if (raw && raw.type === 'add_to_plan') {
      out.push(await applyAddToPlan(userId, ctx, raw));
    }
  }
  return out;
}
